### ISSUE TITLE
MQTT topic `nexus433/sensor/<sensor>/connection` not retained?

### ISSUE THREAD

**Issue by dankeder** [aquaticus/nexus433#43]
If Home Assistant is restarted it will mark the sensors from Nexus433 as unavailable because it doesn't see the `.../connection` topic anymore - only the `.../state` topics are published. If nexus433 is restarted it recovers - nexus433 it will publish messages into the  `.../connection` again (when sensors send something again) and it works.

It looks like messages in the MQTT topic `.../connection` which is used to keep track of the sensor availability in HA are not published with the "retain" flag or it doesn't work properly. 

In order to make it work I had to abuse the "sensor state" topic to get a more reliable availability info:

```
      - name: "Nexus433 CH01 Temperature"
        state_topic: "nexus433/sensor/<sensor>/state"
        value_template: "{{ value_json.temperature }}"
        availability:
          # Normally the availability topic is
          # published only when nexus433 sees the sensor for the first time.
          # If home-assistant is restarted it won't know about the sensor
          # anymore, marking it unavailable. So I abused the "sensor state"
          # topic to get availability from instead.
          # - topic: "nexus433/sensor/801F02656ECF_1000/connection"
          - topic: "nexus433/sensor/801F02656ECF_1000/state"
            value_template: "{{ 'online' if value_json.temperature|is_defined else 'offline' }}"
        expire_after: 300
        force_update: true
```

Thank you for your work keeping this project alive. Let me know if I can help or provide more details.
